// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Commands.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Commands.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace strategy_protocol {

namespace {

const ::google::protobuf::Descriptor* CommandsMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommandsMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* CommandsMessage_Move_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommandsMessage_Move_reflection_ = NULL;
const ::google::protobuf::Descriptor* CommandsMessage_Attack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommandsMessage_Attack_reflection_ = NULL;
const ::google::protobuf::Descriptor* CommandsMessage_Train_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommandsMessage_Train_reflection_ = NULL;
const ::google::protobuf::Descriptor* CommandsMessage_Command_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommandsMessage_Command_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* CommandsMessage_ActorType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* CommandsMessage_CommandType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Commands_2eproto() {
  protobuf_AddDesc_Commands_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Commands.proto");
  GOOGLE_CHECK(file != NULL);
  CommandsMessage_descriptor_ = file->message_type(0);
  static const int CommandsMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage, commands_),
  };
  CommandsMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CommandsMessage_descriptor_,
      CommandsMessage::default_instance_,
      CommandsMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CommandsMessage));
  CommandsMessage_Move_descriptor_ = CommandsMessage_descriptor_->nested_type(0);
  static const int CommandsMessage_Move_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Move, withwhat_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Move, toposition_),
  };
  CommandsMessage_Move_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CommandsMessage_Move_descriptor_,
      CommandsMessage_Move::default_instance_,
      CommandsMessage_Move_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Move, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Move, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CommandsMessage_Move));
  CommandsMessage_Attack_descriptor_ = CommandsMessage_descriptor_->nested_type(1);
  static const int CommandsMessage_Attack_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Attack, withwhat_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Attack, what_),
  };
  CommandsMessage_Attack_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CommandsMessage_Attack_descriptor_,
      CommandsMessage_Attack::default_instance_,
      CommandsMessage_Attack_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Attack, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Attack, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CommandsMessage_Attack));
  CommandsMessage_Train_descriptor_ = CommandsMessage_descriptor_->nested_type(2);
  static const int CommandsMessage_Train_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Train, withwhat_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Train, what_),
  };
  CommandsMessage_Train_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CommandsMessage_Train_descriptor_,
      CommandsMessage_Train::default_instance_,
      CommandsMessage_Train_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Train, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Train, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CommandsMessage_Train));
  CommandsMessage_Command_descriptor_ = CommandsMessage_descriptor_->nested_type(3);
  static const int CommandsMessage_Command_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Command, commandtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Command, movecommand_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Command, attackcommand_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Command, traincommand_),
  };
  CommandsMessage_Command_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CommandsMessage_Command_descriptor_,
      CommandsMessage_Command::default_instance_,
      CommandsMessage_Command_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Command, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandsMessage_Command, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CommandsMessage_Command));
  CommandsMessage_ActorType_descriptor_ = CommandsMessage_descriptor_->enum_type(0);
  CommandsMessage_CommandType_descriptor_ = CommandsMessage_descriptor_->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Commands_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CommandsMessage_descriptor_, &CommandsMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CommandsMessage_Move_descriptor_, &CommandsMessage_Move::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CommandsMessage_Attack_descriptor_, &CommandsMessage_Attack::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CommandsMessage_Train_descriptor_, &CommandsMessage_Train::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CommandsMessage_Command_descriptor_, &CommandsMessage_Command::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Commands_2eproto() {
  delete CommandsMessage::default_instance_;
  delete CommandsMessage_reflection_;
  delete CommandsMessage_Move::default_instance_;
  delete CommandsMessage_Move_reflection_;
  delete CommandsMessage_Attack::default_instance_;
  delete CommandsMessage_Attack_reflection_;
  delete CommandsMessage_Train::default_instance_;
  delete CommandsMessage_Train_reflection_;
  delete CommandsMessage_Command::default_instance_;
  delete CommandsMessage_Command_reflection_;
}

void protobuf_AddDesc_Commands_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::strategy_protocol::protobuf_AddDesc_Common_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016Commands.proto\022\021strategy_protocol\032\014Com"
    "mon.proto\"\202\005\n\017CommandsMessage\022<\n\010command"
    "s\030\001 \003(\0132*.strategy_protocol.CommandsMess"
    "age.Command\032I\n\004Move\022\020\n\010withWhat\030\001 \002(\t\022/\n"
    "\ntoPosition\030\002 \002(\0132\033.strategy_protocol.Po"
    "sition\032(\n\006Attack\022\020\n\010withWhat\030\001 \002(\t\022\014\n\004wh"
    "at\030\002 \002(\t\032U\n\005Train\022\020\n\010withWhat\030\001 \002(\t\022:\n\004w"
    "hat\030\002 \002(\0162,.strategy_protocol.CommandsMe"
    "ssage.ActorType\032\216\002\n\007Command\022C\n\013commandTy"
    "pe\030\001 \002(\0162..strategy_protocol.CommandsMes"
    "sage.CommandType\022<\n\013moveCommand\030\002 \001(\0132\'."
    "strategy_protocol.CommandsMessage.Move\022@"
    "\n\rattackCommand\030\003 \001(\0132).strategy_protoco"
    "l.CommandsMessage.Attack\022>\n\014trainCommand"
    "\030\004 \001(\0132(.strategy_protocol.CommandsMessa"
    "ge.Train\"$\n\tActorType\022\013\n\007SOLDIER\020\000\022\n\n\006WO"
    "RKER\020\001\".\n\013CommandType\022\010\n\004MOVE\020\001\022\n\n\006ATTAC"
    "K\020\002\022\t\n\005TRAIN\020\003", 694);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Commands.proto", &protobuf_RegisterTypes);
  CommandsMessage::default_instance_ = new CommandsMessage();
  CommandsMessage_Move::default_instance_ = new CommandsMessage_Move();
  CommandsMessage_Attack::default_instance_ = new CommandsMessage_Attack();
  CommandsMessage_Train::default_instance_ = new CommandsMessage_Train();
  CommandsMessage_Command::default_instance_ = new CommandsMessage_Command();
  CommandsMessage::default_instance_->InitAsDefaultInstance();
  CommandsMessage_Move::default_instance_->InitAsDefaultInstance();
  CommandsMessage_Attack::default_instance_->InitAsDefaultInstance();
  CommandsMessage_Train::default_instance_->InitAsDefaultInstance();
  CommandsMessage_Command::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Commands_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Commands_2eproto {
  StaticDescriptorInitializer_Commands_2eproto() {
    protobuf_AddDesc_Commands_2eproto();
  }
} static_descriptor_initializer_Commands_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* CommandsMessage_ActorType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommandsMessage_ActorType_descriptor_;
}
bool CommandsMessage_ActorType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const CommandsMessage_ActorType CommandsMessage::SOLDIER;
const CommandsMessage_ActorType CommandsMessage::WORKER;
const CommandsMessage_ActorType CommandsMessage::ActorType_MIN;
const CommandsMessage_ActorType CommandsMessage::ActorType_MAX;
const int CommandsMessage::ActorType_ARRAYSIZE;
#endif  // _MSC_VER
const ::google::protobuf::EnumDescriptor* CommandsMessage_CommandType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommandsMessage_CommandType_descriptor_;
}
bool CommandsMessage_CommandType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const CommandsMessage_CommandType CommandsMessage::MOVE;
const CommandsMessage_CommandType CommandsMessage::ATTACK;
const CommandsMessage_CommandType CommandsMessage::TRAIN;
const CommandsMessage_CommandType CommandsMessage::CommandType_MIN;
const CommandsMessage_CommandType CommandsMessage::CommandType_MAX;
const int CommandsMessage::CommandType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int CommandsMessage_Move::kWithWhatFieldNumber;
const int CommandsMessage_Move::kToPositionFieldNumber;
#endif  // !_MSC_VER

CommandsMessage_Move::CommandsMessage_Move()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CommandsMessage_Move::InitAsDefaultInstance() {
  toposition_ = const_cast< ::strategy_protocol::Position*>(&::strategy_protocol::Position::default_instance());
}

CommandsMessage_Move::CommandsMessage_Move(const CommandsMessage_Move& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CommandsMessage_Move::SharedCtor() {
  _cached_size_ = 0;
  withwhat_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  toposition_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommandsMessage_Move::~CommandsMessage_Move() {
  SharedDtor();
}

void CommandsMessage_Move::SharedDtor() {
  if (withwhat_ != &::google::protobuf::internal::kEmptyString) {
    delete withwhat_;
  }
  if (this != default_instance_) {
    delete toposition_;
  }
}

void CommandsMessage_Move::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommandsMessage_Move::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommandsMessage_Move_descriptor_;
}

const CommandsMessage_Move& CommandsMessage_Move::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Commands_2eproto();
  return *default_instance_;
}

CommandsMessage_Move* CommandsMessage_Move::default_instance_ = NULL;

CommandsMessage_Move* CommandsMessage_Move::New() const {
  return new CommandsMessage_Move;
}

void CommandsMessage_Move::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_withwhat()) {
      if (withwhat_ != &::google::protobuf::internal::kEmptyString) {
        withwhat_->clear();
      }
    }
    if (has_toposition()) {
      if (toposition_ != NULL) toposition_->::strategy_protocol::Position::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CommandsMessage_Move::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string withWhat = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_withwhat()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->withwhat().data(), this->withwhat().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_toPosition;
        break;
      }

      // required .strategy_protocol.Position toPosition = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_toPosition:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_toposition()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CommandsMessage_Move::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string withWhat = 1;
  if (has_withwhat()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->withwhat().data(), this->withwhat().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->withwhat(), output);
  }

  // required .strategy_protocol.Position toPosition = 2;
  if (has_toposition()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->toposition(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CommandsMessage_Move::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string withWhat = 1;
  if (has_withwhat()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->withwhat().data(), this->withwhat().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->withwhat(), target);
  }

  // required .strategy_protocol.Position toPosition = 2;
  if (has_toposition()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->toposition(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CommandsMessage_Move::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string withWhat = 1;
    if (has_withwhat()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->withwhat());
    }

    // required .strategy_protocol.Position toPosition = 2;
    if (has_toposition()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->toposition());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommandsMessage_Move::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CommandsMessage_Move* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CommandsMessage_Move*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommandsMessage_Move::MergeFrom(const CommandsMessage_Move& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_withwhat()) {
      set_withwhat(from.withwhat());
    }
    if (from.has_toposition()) {
      mutable_toposition()->::strategy_protocol::Position::MergeFrom(from.toposition());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CommandsMessage_Move::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandsMessage_Move::CopyFrom(const CommandsMessage_Move& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandsMessage_Move::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_toposition()) {
    if (!this->toposition().IsInitialized()) return false;
  }
  return true;
}

void CommandsMessage_Move::Swap(CommandsMessage_Move* other) {
  if (other != this) {
    std::swap(withwhat_, other->withwhat_);
    std::swap(toposition_, other->toposition_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CommandsMessage_Move::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommandsMessage_Move_descriptor_;
  metadata.reflection = CommandsMessage_Move_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int CommandsMessage_Attack::kWithWhatFieldNumber;
const int CommandsMessage_Attack::kWhatFieldNumber;
#endif  // !_MSC_VER

CommandsMessage_Attack::CommandsMessage_Attack()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CommandsMessage_Attack::InitAsDefaultInstance() {
}

CommandsMessage_Attack::CommandsMessage_Attack(const CommandsMessage_Attack& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CommandsMessage_Attack::SharedCtor() {
  _cached_size_ = 0;
  withwhat_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  what_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommandsMessage_Attack::~CommandsMessage_Attack() {
  SharedDtor();
}

void CommandsMessage_Attack::SharedDtor() {
  if (withwhat_ != &::google::protobuf::internal::kEmptyString) {
    delete withwhat_;
  }
  if (what_ != &::google::protobuf::internal::kEmptyString) {
    delete what_;
  }
  if (this != default_instance_) {
  }
}

void CommandsMessage_Attack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommandsMessage_Attack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommandsMessage_Attack_descriptor_;
}

const CommandsMessage_Attack& CommandsMessage_Attack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Commands_2eproto();
  return *default_instance_;
}

CommandsMessage_Attack* CommandsMessage_Attack::default_instance_ = NULL;

CommandsMessage_Attack* CommandsMessage_Attack::New() const {
  return new CommandsMessage_Attack;
}

void CommandsMessage_Attack::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_withwhat()) {
      if (withwhat_ != &::google::protobuf::internal::kEmptyString) {
        withwhat_->clear();
      }
    }
    if (has_what()) {
      if (what_ != &::google::protobuf::internal::kEmptyString) {
        what_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CommandsMessage_Attack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string withWhat = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_withwhat()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->withwhat().data(), this->withwhat().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_what;
        break;
      }

      // required string what = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_what:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_what()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->what().data(), this->what().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CommandsMessage_Attack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string withWhat = 1;
  if (has_withwhat()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->withwhat().data(), this->withwhat().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->withwhat(), output);
  }

  // required string what = 2;
  if (has_what()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->what().data(), this->what().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->what(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CommandsMessage_Attack::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string withWhat = 1;
  if (has_withwhat()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->withwhat().data(), this->withwhat().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->withwhat(), target);
  }

  // required string what = 2;
  if (has_what()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->what().data(), this->what().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->what(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CommandsMessage_Attack::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string withWhat = 1;
    if (has_withwhat()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->withwhat());
    }

    // required string what = 2;
    if (has_what()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->what());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommandsMessage_Attack::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CommandsMessage_Attack* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CommandsMessage_Attack*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommandsMessage_Attack::MergeFrom(const CommandsMessage_Attack& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_withwhat()) {
      set_withwhat(from.withwhat());
    }
    if (from.has_what()) {
      set_what(from.what());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CommandsMessage_Attack::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandsMessage_Attack::CopyFrom(const CommandsMessage_Attack& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandsMessage_Attack::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void CommandsMessage_Attack::Swap(CommandsMessage_Attack* other) {
  if (other != this) {
    std::swap(withwhat_, other->withwhat_);
    std::swap(what_, other->what_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CommandsMessage_Attack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommandsMessage_Attack_descriptor_;
  metadata.reflection = CommandsMessage_Attack_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int CommandsMessage_Train::kWithWhatFieldNumber;
const int CommandsMessage_Train::kWhatFieldNumber;
#endif  // !_MSC_VER

CommandsMessage_Train::CommandsMessage_Train()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CommandsMessage_Train::InitAsDefaultInstance() {
}

CommandsMessage_Train::CommandsMessage_Train(const CommandsMessage_Train& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CommandsMessage_Train::SharedCtor() {
  _cached_size_ = 0;
  withwhat_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  what_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommandsMessage_Train::~CommandsMessage_Train() {
  SharedDtor();
}

void CommandsMessage_Train::SharedDtor() {
  if (withwhat_ != &::google::protobuf::internal::kEmptyString) {
    delete withwhat_;
  }
  if (this != default_instance_) {
  }
}

void CommandsMessage_Train::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommandsMessage_Train::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommandsMessage_Train_descriptor_;
}

const CommandsMessage_Train& CommandsMessage_Train::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Commands_2eproto();
  return *default_instance_;
}

CommandsMessage_Train* CommandsMessage_Train::default_instance_ = NULL;

CommandsMessage_Train* CommandsMessage_Train::New() const {
  return new CommandsMessage_Train;
}

void CommandsMessage_Train::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_withwhat()) {
      if (withwhat_ != &::google::protobuf::internal::kEmptyString) {
        withwhat_->clear();
      }
    }
    what_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CommandsMessage_Train::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string withWhat = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_withwhat()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->withwhat().data(), this->withwhat().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_what;
        break;
      }

      // required .strategy_protocol.CommandsMessage.ActorType what = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_what:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::strategy_protocol::CommandsMessage_ActorType_IsValid(value)) {
            set_what(static_cast< ::strategy_protocol::CommandsMessage_ActorType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CommandsMessage_Train::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string withWhat = 1;
  if (has_withwhat()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->withwhat().data(), this->withwhat().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->withwhat(), output);
  }

  // required .strategy_protocol.CommandsMessage.ActorType what = 2;
  if (has_what()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->what(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CommandsMessage_Train::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string withWhat = 1;
  if (has_withwhat()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->withwhat().data(), this->withwhat().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->withwhat(), target);
  }

  // required .strategy_protocol.CommandsMessage.ActorType what = 2;
  if (has_what()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->what(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CommandsMessage_Train::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string withWhat = 1;
    if (has_withwhat()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->withwhat());
    }

    // required .strategy_protocol.CommandsMessage.ActorType what = 2;
    if (has_what()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->what());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommandsMessage_Train::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CommandsMessage_Train* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CommandsMessage_Train*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommandsMessage_Train::MergeFrom(const CommandsMessage_Train& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_withwhat()) {
      set_withwhat(from.withwhat());
    }
    if (from.has_what()) {
      set_what(from.what());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CommandsMessage_Train::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandsMessage_Train::CopyFrom(const CommandsMessage_Train& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandsMessage_Train::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void CommandsMessage_Train::Swap(CommandsMessage_Train* other) {
  if (other != this) {
    std::swap(withwhat_, other->withwhat_);
    std::swap(what_, other->what_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CommandsMessage_Train::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommandsMessage_Train_descriptor_;
  metadata.reflection = CommandsMessage_Train_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int CommandsMessage_Command::kCommandTypeFieldNumber;
const int CommandsMessage_Command::kMoveCommandFieldNumber;
const int CommandsMessage_Command::kAttackCommandFieldNumber;
const int CommandsMessage_Command::kTrainCommandFieldNumber;
#endif  // !_MSC_VER

CommandsMessage_Command::CommandsMessage_Command()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CommandsMessage_Command::InitAsDefaultInstance() {
  movecommand_ = const_cast< ::strategy_protocol::CommandsMessage_Move*>(&::strategy_protocol::CommandsMessage_Move::default_instance());
  attackcommand_ = const_cast< ::strategy_protocol::CommandsMessage_Attack*>(&::strategy_protocol::CommandsMessage_Attack::default_instance());
  traincommand_ = const_cast< ::strategy_protocol::CommandsMessage_Train*>(&::strategy_protocol::CommandsMessage_Train::default_instance());
}

CommandsMessage_Command::CommandsMessage_Command(const CommandsMessage_Command& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CommandsMessage_Command::SharedCtor() {
  _cached_size_ = 0;
  commandtype_ = 1;
  movecommand_ = NULL;
  attackcommand_ = NULL;
  traincommand_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommandsMessage_Command::~CommandsMessage_Command() {
  SharedDtor();
}

void CommandsMessage_Command::SharedDtor() {
  if (this != default_instance_) {
    delete movecommand_;
    delete attackcommand_;
    delete traincommand_;
  }
}

void CommandsMessage_Command::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommandsMessage_Command::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommandsMessage_Command_descriptor_;
}

const CommandsMessage_Command& CommandsMessage_Command::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Commands_2eproto();
  return *default_instance_;
}

CommandsMessage_Command* CommandsMessage_Command::default_instance_ = NULL;

CommandsMessage_Command* CommandsMessage_Command::New() const {
  return new CommandsMessage_Command;
}

void CommandsMessage_Command::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    commandtype_ = 1;
    if (has_movecommand()) {
      if (movecommand_ != NULL) movecommand_->::strategy_protocol::CommandsMessage_Move::Clear();
    }
    if (has_attackcommand()) {
      if (attackcommand_ != NULL) attackcommand_->::strategy_protocol::CommandsMessage_Attack::Clear();
    }
    if (has_traincommand()) {
      if (traincommand_ != NULL) traincommand_->::strategy_protocol::CommandsMessage_Train::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CommandsMessage_Command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .strategy_protocol.CommandsMessage.CommandType commandType = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::strategy_protocol::CommandsMessage_CommandType_IsValid(value)) {
            set_commandtype(static_cast< ::strategy_protocol::CommandsMessage_CommandType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_moveCommand;
        break;
      }

      // optional .strategy_protocol.CommandsMessage.Move moveCommand = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_moveCommand:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_movecommand()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_attackCommand;
        break;
      }

      // optional .strategy_protocol.CommandsMessage.Attack attackCommand = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_attackCommand:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_attackcommand()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_trainCommand;
        break;
      }

      // optional .strategy_protocol.CommandsMessage.Train trainCommand = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_trainCommand:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_traincommand()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CommandsMessage_Command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .strategy_protocol.CommandsMessage.CommandType commandType = 1;
  if (has_commandtype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->commandtype(), output);
  }

  // optional .strategy_protocol.CommandsMessage.Move moveCommand = 2;
  if (has_movecommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->movecommand(), output);
  }

  // optional .strategy_protocol.CommandsMessage.Attack attackCommand = 3;
  if (has_attackcommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->attackcommand(), output);
  }

  // optional .strategy_protocol.CommandsMessage.Train trainCommand = 4;
  if (has_traincommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->traincommand(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CommandsMessage_Command::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .strategy_protocol.CommandsMessage.CommandType commandType = 1;
  if (has_commandtype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->commandtype(), target);
  }

  // optional .strategy_protocol.CommandsMessage.Move moveCommand = 2;
  if (has_movecommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->movecommand(), target);
  }

  // optional .strategy_protocol.CommandsMessage.Attack attackCommand = 3;
  if (has_attackcommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->attackcommand(), target);
  }

  // optional .strategy_protocol.CommandsMessage.Train trainCommand = 4;
  if (has_traincommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->traincommand(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CommandsMessage_Command::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .strategy_protocol.CommandsMessage.CommandType commandType = 1;
    if (has_commandtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->commandtype());
    }

    // optional .strategy_protocol.CommandsMessage.Move moveCommand = 2;
    if (has_movecommand()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->movecommand());
    }

    // optional .strategy_protocol.CommandsMessage.Attack attackCommand = 3;
    if (has_attackcommand()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->attackcommand());
    }

    // optional .strategy_protocol.CommandsMessage.Train trainCommand = 4;
    if (has_traincommand()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->traincommand());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommandsMessage_Command::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CommandsMessage_Command* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CommandsMessage_Command*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommandsMessage_Command::MergeFrom(const CommandsMessage_Command& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_commandtype()) {
      set_commandtype(from.commandtype());
    }
    if (from.has_movecommand()) {
      mutable_movecommand()->::strategy_protocol::CommandsMessage_Move::MergeFrom(from.movecommand());
    }
    if (from.has_attackcommand()) {
      mutable_attackcommand()->::strategy_protocol::CommandsMessage_Attack::MergeFrom(from.attackcommand());
    }
    if (from.has_traincommand()) {
      mutable_traincommand()->::strategy_protocol::CommandsMessage_Train::MergeFrom(from.traincommand());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CommandsMessage_Command::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandsMessage_Command::CopyFrom(const CommandsMessage_Command& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandsMessage_Command::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_movecommand()) {
    if (!this->movecommand().IsInitialized()) return false;
  }
  if (has_attackcommand()) {
    if (!this->attackcommand().IsInitialized()) return false;
  }
  if (has_traincommand()) {
    if (!this->traincommand().IsInitialized()) return false;
  }
  return true;
}

void CommandsMessage_Command::Swap(CommandsMessage_Command* other) {
  if (other != this) {
    std::swap(commandtype_, other->commandtype_);
    std::swap(movecommand_, other->movecommand_);
    std::swap(attackcommand_, other->attackcommand_);
    std::swap(traincommand_, other->traincommand_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CommandsMessage_Command::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommandsMessage_Command_descriptor_;
  metadata.reflection = CommandsMessage_Command_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int CommandsMessage::kCommandsFieldNumber;
#endif  // !_MSC_VER

CommandsMessage::CommandsMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CommandsMessage::InitAsDefaultInstance() {
}

CommandsMessage::CommandsMessage(const CommandsMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CommandsMessage::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommandsMessage::~CommandsMessage() {
  SharedDtor();
}

void CommandsMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CommandsMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommandsMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommandsMessage_descriptor_;
}

const CommandsMessage& CommandsMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Commands_2eproto();
  return *default_instance_;
}

CommandsMessage* CommandsMessage::default_instance_ = NULL;

CommandsMessage* CommandsMessage::New() const {
  return new CommandsMessage;
}

void CommandsMessage::Clear() {
  commands_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CommandsMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .strategy_protocol.CommandsMessage.Command commands = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_commands:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_commands()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_commands;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CommandsMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .strategy_protocol.CommandsMessage.Command commands = 1;
  for (int i = 0; i < this->commands_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->commands(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CommandsMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .strategy_protocol.CommandsMessage.Command commands = 1;
  for (int i = 0; i < this->commands_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->commands(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CommandsMessage::ByteSize() const {
  int total_size = 0;

  // repeated .strategy_protocol.CommandsMessage.Command commands = 1;
  total_size += 1 * this->commands_size();
  for (int i = 0; i < this->commands_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->commands(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommandsMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CommandsMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CommandsMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommandsMessage::MergeFrom(const CommandsMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  commands_.MergeFrom(from.commands_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CommandsMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandsMessage::CopyFrom(const CommandsMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandsMessage::IsInitialized() const {

  for (int i = 0; i < commands_size(); i++) {
    if (!this->commands(i).IsInitialized()) return false;
  }
  return true;
}

void CommandsMessage::Swap(CommandsMessage* other) {
  if (other != this) {
    commands_.Swap(&other->commands_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CommandsMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommandsMessage_descriptor_;
  metadata.reflection = CommandsMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace strategy_protocol

// @@protoc_insertion_point(global_scope)
