// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldStatusUpdate.proto

#ifndef PROTOBUF_WorldStatusUpdate_2eproto__INCLUDED
#define PROTOBUF_WorldStatusUpdate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "Common.pb.h"
// @@protoc_insertion_point(includes)

namespace strategy_protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_WorldStatusUpdate_2eproto();
void protobuf_AssignDesc_WorldStatusUpdate_2eproto();
void protobuf_ShutdownFile_WorldStatusUpdate_2eproto();

class WorldStatusUpdateMessage;
class WorldStatusUpdateMessage_CommonProperties;
class WorldStatusUpdateMessage_Base;
class WorldStatusUpdateMessage_Mine;
class WorldStatusUpdateMessage_Obstacle;
class WorldStatusUpdateMessage_Worker;
class WorldStatusUpdateMessage_Soldier;

// ===================================================================

class WorldStatusUpdateMessage_CommonProperties : public ::google::protobuf::Message {
 public:
  WorldStatusUpdateMessage_CommonProperties();
  virtual ~WorldStatusUpdateMessage_CommonProperties();

  WorldStatusUpdateMessage_CommonProperties(const WorldStatusUpdateMessage_CommonProperties& from);

  inline WorldStatusUpdateMessage_CommonProperties& operator=(const WorldStatusUpdateMessage_CommonProperties& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorldStatusUpdateMessage_CommonProperties& default_instance();

  void Swap(WorldStatusUpdateMessage_CommonProperties* other);

  // implements Message ----------------------------------------------

  WorldStatusUpdateMessage_CommonProperties* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorldStatusUpdateMessage_CommonProperties& from);
  void MergeFrom(const WorldStatusUpdateMessage_CommonProperties& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline const ::std::string& id() const;
  inline void set_id(const ::std::string& value);
  inline void set_id(const char* value);
  inline void set_id(const char* value, size_t size);
  inline ::std::string* mutable_id();
  inline ::std::string* release_id();
  inline void set_allocated_id(::std::string* id);

  // optional .strategy_protocol.Position position = 2;
  inline bool has_position() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 2;
  inline const ::strategy_protocol::Position& position() const;
  inline ::strategy_protocol::Position* mutable_position();
  inline ::strategy_protocol::Position* release_position();
  inline void set_allocated_position(::strategy_protocol::Position* position);

  // @@protoc_insertion_point(class_scope:strategy_protocol.WorldStatusUpdateMessage.CommonProperties)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_position();
  inline void clear_has_position();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* id_;
  ::strategy_protocol::Position* position_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_AssignDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_ShutdownFile_WorldStatusUpdate_2eproto();

  void InitAsDefaultInstance();
  static WorldStatusUpdateMessage_CommonProperties* default_instance_;
};
// -------------------------------------------------------------------

class WorldStatusUpdateMessage_Base : public ::google::protobuf::Message {
 public:
  WorldStatusUpdateMessage_Base();
  virtual ~WorldStatusUpdateMessage_Base();

  WorldStatusUpdateMessage_Base(const WorldStatusUpdateMessage_Base& from);

  inline WorldStatusUpdateMessage_Base& operator=(const WorldStatusUpdateMessage_Base& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorldStatusUpdateMessage_Base& default_instance();

  void Swap(WorldStatusUpdateMessage_Base* other);

  // implements Message ----------------------------------------------

  WorldStatusUpdateMessage_Base* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorldStatusUpdateMessage_Base& from);
  void MergeFrom(const WorldStatusUpdateMessage_Base& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .strategy_protocol.WorldStatusUpdateMessage.CommonProperties common = 1;
  inline bool has_common() const;
  inline void clear_common();
  static const int kCommonFieldNumber = 1;
  inline const ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties& common() const;
  inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* mutable_common();
  inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* release_common();
  inline void set_allocated_common(::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common);

  // optional int32 health = 2;
  inline bool has_health() const;
  inline void clear_health();
  static const int kHealthFieldNumber = 2;
  inline ::google::protobuf::int32 health() const;
  inline void set_health(::google::protobuf::int32 value);

  // optional int32 team = 3;
  inline bool has_team() const;
  inline void clear_team();
  static const int kTeamFieldNumber = 3;
  inline ::google::protobuf::int32 team() const;
  inline void set_team(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:strategy_protocol.WorldStatusUpdateMessage.Base)
 private:
  inline void set_has_common();
  inline void clear_has_common();
  inline void set_has_health();
  inline void clear_has_health();
  inline void set_has_team();
  inline void clear_has_team();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common_;
  ::google::protobuf::int32 health_;
  ::google::protobuf::int32 team_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_AssignDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_ShutdownFile_WorldStatusUpdate_2eproto();

  void InitAsDefaultInstance();
  static WorldStatusUpdateMessage_Base* default_instance_;
};
// -------------------------------------------------------------------

class WorldStatusUpdateMessage_Mine : public ::google::protobuf::Message {
 public:
  WorldStatusUpdateMessage_Mine();
  virtual ~WorldStatusUpdateMessage_Mine();

  WorldStatusUpdateMessage_Mine(const WorldStatusUpdateMessage_Mine& from);

  inline WorldStatusUpdateMessage_Mine& operator=(const WorldStatusUpdateMessage_Mine& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorldStatusUpdateMessage_Mine& default_instance();

  void Swap(WorldStatusUpdateMessage_Mine* other);

  // implements Message ----------------------------------------------

  WorldStatusUpdateMessage_Mine* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorldStatusUpdateMessage_Mine& from);
  void MergeFrom(const WorldStatusUpdateMessage_Mine& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .strategy_protocol.WorldStatusUpdateMessage.CommonProperties common = 1;
  inline bool has_common() const;
  inline void clear_common();
  static const int kCommonFieldNumber = 1;
  inline const ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties& common() const;
  inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* mutable_common();
  inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* release_common();
  inline void set_allocated_common(::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common);

  // optional int32 capacity = 2;
  inline bool has_capacity() const;
  inline void clear_capacity();
  static const int kCapacityFieldNumber = 2;
  inline ::google::protobuf::int32 capacity() const;
  inline void set_capacity(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:strategy_protocol.WorldStatusUpdateMessage.Mine)
 private:
  inline void set_has_common();
  inline void clear_has_common();
  inline void set_has_capacity();
  inline void clear_has_capacity();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common_;
  ::google::protobuf::int32 capacity_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_AssignDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_ShutdownFile_WorldStatusUpdate_2eproto();

  void InitAsDefaultInstance();
  static WorldStatusUpdateMessage_Mine* default_instance_;
};
// -------------------------------------------------------------------

class WorldStatusUpdateMessage_Obstacle : public ::google::protobuf::Message {
 public:
  WorldStatusUpdateMessage_Obstacle();
  virtual ~WorldStatusUpdateMessage_Obstacle();

  WorldStatusUpdateMessage_Obstacle(const WorldStatusUpdateMessage_Obstacle& from);

  inline WorldStatusUpdateMessage_Obstacle& operator=(const WorldStatusUpdateMessage_Obstacle& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorldStatusUpdateMessage_Obstacle& default_instance();

  void Swap(WorldStatusUpdateMessage_Obstacle* other);

  // implements Message ----------------------------------------------

  WorldStatusUpdateMessage_Obstacle* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorldStatusUpdateMessage_Obstacle& from);
  void MergeFrom(const WorldStatusUpdateMessage_Obstacle& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .strategy_protocol.WorldStatusUpdateMessage.CommonProperties common = 1;
  inline bool has_common() const;
  inline void clear_common();
  static const int kCommonFieldNumber = 1;
  inline const ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties& common() const;
  inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* mutable_common();
  inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* release_common();
  inline void set_allocated_common(::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common);

  // @@protoc_insertion_point(class_scope:strategy_protocol.WorldStatusUpdateMessage.Obstacle)
 private:
  inline void set_has_common();
  inline void clear_has_common();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_AssignDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_ShutdownFile_WorldStatusUpdate_2eproto();

  void InitAsDefaultInstance();
  static WorldStatusUpdateMessage_Obstacle* default_instance_;
};
// -------------------------------------------------------------------

class WorldStatusUpdateMessage_Worker : public ::google::protobuf::Message {
 public:
  WorldStatusUpdateMessage_Worker();
  virtual ~WorldStatusUpdateMessage_Worker();

  WorldStatusUpdateMessage_Worker(const WorldStatusUpdateMessage_Worker& from);

  inline WorldStatusUpdateMessage_Worker& operator=(const WorldStatusUpdateMessage_Worker& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorldStatusUpdateMessage_Worker& default_instance();

  void Swap(WorldStatusUpdateMessage_Worker* other);

  // implements Message ----------------------------------------------

  WorldStatusUpdateMessage_Worker* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorldStatusUpdateMessage_Worker& from);
  void MergeFrom(const WorldStatusUpdateMessage_Worker& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .strategy_protocol.WorldStatusUpdateMessage.CommonProperties common = 1;
  inline bool has_common() const;
  inline void clear_common();
  static const int kCommonFieldNumber = 1;
  inline const ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties& common() const;
  inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* mutable_common();
  inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* release_common();
  inline void set_allocated_common(::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common);

  // optional int32 resource = 2;
  inline bool has_resource() const;
  inline void clear_resource();
  static const int kResourceFieldNumber = 2;
  inline ::google::protobuf::int32 resource() const;
  inline void set_resource(::google::protobuf::int32 value);

  // optional int32 health = 3;
  inline bool has_health() const;
  inline void clear_health();
  static const int kHealthFieldNumber = 3;
  inline ::google::protobuf::int32 health() const;
  inline void set_health(::google::protobuf::int32 value);

  // optional int32 team = 4;
  inline bool has_team() const;
  inline void clear_team();
  static const int kTeamFieldNumber = 4;
  inline ::google::protobuf::int32 team() const;
  inline void set_team(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:strategy_protocol.WorldStatusUpdateMessage.Worker)
 private:
  inline void set_has_common();
  inline void clear_has_common();
  inline void set_has_resource();
  inline void clear_has_resource();
  inline void set_has_health();
  inline void clear_has_health();
  inline void set_has_team();
  inline void clear_has_team();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common_;
  ::google::protobuf::int32 resource_;
  ::google::protobuf::int32 health_;
  ::google::protobuf::int32 team_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_AssignDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_ShutdownFile_WorldStatusUpdate_2eproto();

  void InitAsDefaultInstance();
  static WorldStatusUpdateMessage_Worker* default_instance_;
};
// -------------------------------------------------------------------

class WorldStatusUpdateMessage_Soldier : public ::google::protobuf::Message {
 public:
  WorldStatusUpdateMessage_Soldier();
  virtual ~WorldStatusUpdateMessage_Soldier();

  WorldStatusUpdateMessage_Soldier(const WorldStatusUpdateMessage_Soldier& from);

  inline WorldStatusUpdateMessage_Soldier& operator=(const WorldStatusUpdateMessage_Soldier& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorldStatusUpdateMessage_Soldier& default_instance();

  void Swap(WorldStatusUpdateMessage_Soldier* other);

  // implements Message ----------------------------------------------

  WorldStatusUpdateMessage_Soldier* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorldStatusUpdateMessage_Soldier& from);
  void MergeFrom(const WorldStatusUpdateMessage_Soldier& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .strategy_protocol.WorldStatusUpdateMessage.CommonProperties common = 1;
  inline bool has_common() const;
  inline void clear_common();
  static const int kCommonFieldNumber = 1;
  inline const ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties& common() const;
  inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* mutable_common();
  inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* release_common();
  inline void set_allocated_common(::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common);

  // optional int32 health = 2;
  inline bool has_health() const;
  inline void clear_health();
  static const int kHealthFieldNumber = 2;
  inline ::google::protobuf::int32 health() const;
  inline void set_health(::google::protobuf::int32 value);

  // optional int32 team = 3;
  inline bool has_team() const;
  inline void clear_team();
  static const int kTeamFieldNumber = 3;
  inline ::google::protobuf::int32 team() const;
  inline void set_team(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:strategy_protocol.WorldStatusUpdateMessage.Soldier)
 private:
  inline void set_has_common();
  inline void clear_has_common();
  inline void set_has_health();
  inline void clear_has_health();
  inline void set_has_team();
  inline void clear_has_team();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common_;
  ::google::protobuf::int32 health_;
  ::google::protobuf::int32 team_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_AssignDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_ShutdownFile_WorldStatusUpdate_2eproto();

  void InitAsDefaultInstance();
  static WorldStatusUpdateMessage_Soldier* default_instance_;
};
// -------------------------------------------------------------------

class WorldStatusUpdateMessage : public ::google::protobuf::Message {
 public:
  WorldStatusUpdateMessage();
  virtual ~WorldStatusUpdateMessage();

  WorldStatusUpdateMessage(const WorldStatusUpdateMessage& from);

  inline WorldStatusUpdateMessage& operator=(const WorldStatusUpdateMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorldStatusUpdateMessage& default_instance();

  void Swap(WorldStatusUpdateMessage* other);

  // implements Message ----------------------------------------------

  WorldStatusUpdateMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorldStatusUpdateMessage& from);
  void MergeFrom(const WorldStatusUpdateMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef WorldStatusUpdateMessage_CommonProperties CommonProperties;
  typedef WorldStatusUpdateMessage_Base Base;
  typedef WorldStatusUpdateMessage_Mine Mine;
  typedef WorldStatusUpdateMessage_Obstacle Obstacle;
  typedef WorldStatusUpdateMessage_Worker Worker;
  typedef WorldStatusUpdateMessage_Soldier Soldier;

  // accessors -------------------------------------------------------

  // repeated .strategy_protocol.WorldStatusUpdateMessage.Base bases = 1;
  inline int bases_size() const;
  inline void clear_bases();
  static const int kBasesFieldNumber = 1;
  inline const ::strategy_protocol::WorldStatusUpdateMessage_Base& bases(int index) const;
  inline ::strategy_protocol::WorldStatusUpdateMessage_Base* mutable_bases(int index);
  inline ::strategy_protocol::WorldStatusUpdateMessage_Base* add_bases();
  inline const ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Base >&
      bases() const;
  inline ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Base >*
      mutable_bases();

  // repeated .strategy_protocol.WorldStatusUpdateMessage.Mine mines = 2;
  inline int mines_size() const;
  inline void clear_mines();
  static const int kMinesFieldNumber = 2;
  inline const ::strategy_protocol::WorldStatusUpdateMessage_Mine& mines(int index) const;
  inline ::strategy_protocol::WorldStatusUpdateMessage_Mine* mutable_mines(int index);
  inline ::strategy_protocol::WorldStatusUpdateMessage_Mine* add_mines();
  inline const ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Mine >&
      mines() const;
  inline ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Mine >*
      mutable_mines();

  // repeated .strategy_protocol.WorldStatusUpdateMessage.Obstacle obstacles = 3;
  inline int obstacles_size() const;
  inline void clear_obstacles();
  static const int kObstaclesFieldNumber = 3;
  inline const ::strategy_protocol::WorldStatusUpdateMessage_Obstacle& obstacles(int index) const;
  inline ::strategy_protocol::WorldStatusUpdateMessage_Obstacle* mutable_obstacles(int index);
  inline ::strategy_protocol::WorldStatusUpdateMessage_Obstacle* add_obstacles();
  inline const ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Obstacle >&
      obstacles() const;
  inline ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Obstacle >*
      mutable_obstacles();

  // repeated .strategy_protocol.WorldStatusUpdateMessage.Worker workers = 4;
  inline int workers_size() const;
  inline void clear_workers();
  static const int kWorkersFieldNumber = 4;
  inline const ::strategy_protocol::WorldStatusUpdateMessage_Worker& workers(int index) const;
  inline ::strategy_protocol::WorldStatusUpdateMessage_Worker* mutable_workers(int index);
  inline ::strategy_protocol::WorldStatusUpdateMessage_Worker* add_workers();
  inline const ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Worker >&
      workers() const;
  inline ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Worker >*
      mutable_workers();

  // repeated .strategy_protocol.WorldStatusUpdateMessage.Soldier soldiers = 5;
  inline int soldiers_size() const;
  inline void clear_soldiers();
  static const int kSoldiersFieldNumber = 5;
  inline const ::strategy_protocol::WorldStatusUpdateMessage_Soldier& soldiers(int index) const;
  inline ::strategy_protocol::WorldStatusUpdateMessage_Soldier* mutable_soldiers(int index);
  inline ::strategy_protocol::WorldStatusUpdateMessage_Soldier* add_soldiers();
  inline const ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Soldier >&
      soldiers() const;
  inline ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Soldier >*
      mutable_soldiers();

  // optional int32 resource = 6;
  inline bool has_resource() const;
  inline void clear_resource();
  static const int kResourceFieldNumber = 6;
  inline ::google::protobuf::int32 resource() const;
  inline void set_resource(::google::protobuf::int32 value);

  // optional int32 myteam = 7;
  inline bool has_myteam() const;
  inline void clear_myteam();
  static const int kMyteamFieldNumber = 7;
  inline ::google::protobuf::int32 myteam() const;
  inline void set_myteam(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:strategy_protocol.WorldStatusUpdateMessage)
 private:
  inline void set_has_resource();
  inline void clear_has_resource();
  inline void set_has_myteam();
  inline void clear_has_myteam();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Base > bases_;
  ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Mine > mines_;
  ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Obstacle > obstacles_;
  ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Worker > workers_;
  ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Soldier > soldiers_;
  ::google::protobuf::int32 resource_;
  ::google::protobuf::int32 myteam_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_AssignDesc_WorldStatusUpdate_2eproto();
  friend void protobuf_ShutdownFile_WorldStatusUpdate_2eproto();

  void InitAsDefaultInstance();
  static WorldStatusUpdateMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// WorldStatusUpdateMessage_CommonProperties

// optional string id = 1;
inline bool WorldStatusUpdateMessage_CommonProperties::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WorldStatusUpdateMessage_CommonProperties::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WorldStatusUpdateMessage_CommonProperties::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WorldStatusUpdateMessage_CommonProperties::clear_id() {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    id_->clear();
  }
  clear_has_id();
}
inline const ::std::string& WorldStatusUpdateMessage_CommonProperties::id() const {
  return *id_;
}
inline void WorldStatusUpdateMessage_CommonProperties::set_id(const ::std::string& value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void WorldStatusUpdateMessage_CommonProperties::set_id(const char* value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void WorldStatusUpdateMessage_CommonProperties::set_id(const char* value, size_t size) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* WorldStatusUpdateMessage_CommonProperties::mutable_id() {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  return id_;
}
inline ::std::string* WorldStatusUpdateMessage_CommonProperties::release_id() {
  clear_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = id_;
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void WorldStatusUpdateMessage_CommonProperties::set_allocated_id(::std::string* id) {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    delete id_;
  }
  if (id) {
    set_has_id();
    id_ = id;
  } else {
    clear_has_id();
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .strategy_protocol.Position position = 2;
inline bool WorldStatusUpdateMessage_CommonProperties::has_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WorldStatusUpdateMessage_CommonProperties::set_has_position() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WorldStatusUpdateMessage_CommonProperties::clear_has_position() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WorldStatusUpdateMessage_CommonProperties::clear_position() {
  if (position_ != NULL) position_->::strategy_protocol::Position::Clear();
  clear_has_position();
}
inline const ::strategy_protocol::Position& WorldStatusUpdateMessage_CommonProperties::position() const {
  return position_ != NULL ? *position_ : *default_instance_->position_;
}
inline ::strategy_protocol::Position* WorldStatusUpdateMessage_CommonProperties::mutable_position() {
  set_has_position();
  if (position_ == NULL) position_ = new ::strategy_protocol::Position;
  return position_;
}
inline ::strategy_protocol::Position* WorldStatusUpdateMessage_CommonProperties::release_position() {
  clear_has_position();
  ::strategy_protocol::Position* temp = position_;
  position_ = NULL;
  return temp;
}
inline void WorldStatusUpdateMessage_CommonProperties::set_allocated_position(::strategy_protocol::Position* position) {
  delete position_;
  position_ = position;
  if (position) {
    set_has_position();
  } else {
    clear_has_position();
  }
}

// -------------------------------------------------------------------

// WorldStatusUpdateMessage_Base

// optional .strategy_protocol.WorldStatusUpdateMessage.CommonProperties common = 1;
inline bool WorldStatusUpdateMessage_Base::has_common() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WorldStatusUpdateMessage_Base::set_has_common() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WorldStatusUpdateMessage_Base::clear_has_common() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WorldStatusUpdateMessage_Base::clear_common() {
  if (common_ != NULL) common_->::strategy_protocol::WorldStatusUpdateMessage_CommonProperties::Clear();
  clear_has_common();
}
inline const ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties& WorldStatusUpdateMessage_Base::common() const {
  return common_ != NULL ? *common_ : *default_instance_->common_;
}
inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* WorldStatusUpdateMessage_Base::mutable_common() {
  set_has_common();
  if (common_ == NULL) common_ = new ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties;
  return common_;
}
inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* WorldStatusUpdateMessage_Base::release_common() {
  clear_has_common();
  ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* temp = common_;
  common_ = NULL;
  return temp;
}
inline void WorldStatusUpdateMessage_Base::set_allocated_common(::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common) {
  delete common_;
  common_ = common;
  if (common) {
    set_has_common();
  } else {
    clear_has_common();
  }
}

// optional int32 health = 2;
inline bool WorldStatusUpdateMessage_Base::has_health() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WorldStatusUpdateMessage_Base::set_has_health() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WorldStatusUpdateMessage_Base::clear_has_health() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WorldStatusUpdateMessage_Base::clear_health() {
  health_ = 0;
  clear_has_health();
}
inline ::google::protobuf::int32 WorldStatusUpdateMessage_Base::health() const {
  return health_;
}
inline void WorldStatusUpdateMessage_Base::set_health(::google::protobuf::int32 value) {
  set_has_health();
  health_ = value;
}

// optional int32 team = 3;
inline bool WorldStatusUpdateMessage_Base::has_team() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WorldStatusUpdateMessage_Base::set_has_team() {
  _has_bits_[0] |= 0x00000004u;
}
inline void WorldStatusUpdateMessage_Base::clear_has_team() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void WorldStatusUpdateMessage_Base::clear_team() {
  team_ = 0;
  clear_has_team();
}
inline ::google::protobuf::int32 WorldStatusUpdateMessage_Base::team() const {
  return team_;
}
inline void WorldStatusUpdateMessage_Base::set_team(::google::protobuf::int32 value) {
  set_has_team();
  team_ = value;
}

// -------------------------------------------------------------------

// WorldStatusUpdateMessage_Mine

// optional .strategy_protocol.WorldStatusUpdateMessage.CommonProperties common = 1;
inline bool WorldStatusUpdateMessage_Mine::has_common() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WorldStatusUpdateMessage_Mine::set_has_common() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WorldStatusUpdateMessage_Mine::clear_has_common() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WorldStatusUpdateMessage_Mine::clear_common() {
  if (common_ != NULL) common_->::strategy_protocol::WorldStatusUpdateMessage_CommonProperties::Clear();
  clear_has_common();
}
inline const ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties& WorldStatusUpdateMessage_Mine::common() const {
  return common_ != NULL ? *common_ : *default_instance_->common_;
}
inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* WorldStatusUpdateMessage_Mine::mutable_common() {
  set_has_common();
  if (common_ == NULL) common_ = new ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties;
  return common_;
}
inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* WorldStatusUpdateMessage_Mine::release_common() {
  clear_has_common();
  ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* temp = common_;
  common_ = NULL;
  return temp;
}
inline void WorldStatusUpdateMessage_Mine::set_allocated_common(::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common) {
  delete common_;
  common_ = common;
  if (common) {
    set_has_common();
  } else {
    clear_has_common();
  }
}

// optional int32 capacity = 2;
inline bool WorldStatusUpdateMessage_Mine::has_capacity() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WorldStatusUpdateMessage_Mine::set_has_capacity() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WorldStatusUpdateMessage_Mine::clear_has_capacity() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WorldStatusUpdateMessage_Mine::clear_capacity() {
  capacity_ = 0;
  clear_has_capacity();
}
inline ::google::protobuf::int32 WorldStatusUpdateMessage_Mine::capacity() const {
  return capacity_;
}
inline void WorldStatusUpdateMessage_Mine::set_capacity(::google::protobuf::int32 value) {
  set_has_capacity();
  capacity_ = value;
}

// -------------------------------------------------------------------

// WorldStatusUpdateMessage_Obstacle

// optional .strategy_protocol.WorldStatusUpdateMessage.CommonProperties common = 1;
inline bool WorldStatusUpdateMessage_Obstacle::has_common() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WorldStatusUpdateMessage_Obstacle::set_has_common() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WorldStatusUpdateMessage_Obstacle::clear_has_common() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WorldStatusUpdateMessage_Obstacle::clear_common() {
  if (common_ != NULL) common_->::strategy_protocol::WorldStatusUpdateMessage_CommonProperties::Clear();
  clear_has_common();
}
inline const ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties& WorldStatusUpdateMessage_Obstacle::common() const {
  return common_ != NULL ? *common_ : *default_instance_->common_;
}
inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* WorldStatusUpdateMessage_Obstacle::mutable_common() {
  set_has_common();
  if (common_ == NULL) common_ = new ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties;
  return common_;
}
inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* WorldStatusUpdateMessage_Obstacle::release_common() {
  clear_has_common();
  ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* temp = common_;
  common_ = NULL;
  return temp;
}
inline void WorldStatusUpdateMessage_Obstacle::set_allocated_common(::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common) {
  delete common_;
  common_ = common;
  if (common) {
    set_has_common();
  } else {
    clear_has_common();
  }
}

// -------------------------------------------------------------------

// WorldStatusUpdateMessage_Worker

// optional .strategy_protocol.WorldStatusUpdateMessage.CommonProperties common = 1;
inline bool WorldStatusUpdateMessage_Worker::has_common() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WorldStatusUpdateMessage_Worker::set_has_common() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WorldStatusUpdateMessage_Worker::clear_has_common() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WorldStatusUpdateMessage_Worker::clear_common() {
  if (common_ != NULL) common_->::strategy_protocol::WorldStatusUpdateMessage_CommonProperties::Clear();
  clear_has_common();
}
inline const ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties& WorldStatusUpdateMessage_Worker::common() const {
  return common_ != NULL ? *common_ : *default_instance_->common_;
}
inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* WorldStatusUpdateMessage_Worker::mutable_common() {
  set_has_common();
  if (common_ == NULL) common_ = new ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties;
  return common_;
}
inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* WorldStatusUpdateMessage_Worker::release_common() {
  clear_has_common();
  ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* temp = common_;
  common_ = NULL;
  return temp;
}
inline void WorldStatusUpdateMessage_Worker::set_allocated_common(::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common) {
  delete common_;
  common_ = common;
  if (common) {
    set_has_common();
  } else {
    clear_has_common();
  }
}

// optional int32 resource = 2;
inline bool WorldStatusUpdateMessage_Worker::has_resource() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WorldStatusUpdateMessage_Worker::set_has_resource() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WorldStatusUpdateMessage_Worker::clear_has_resource() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WorldStatusUpdateMessage_Worker::clear_resource() {
  resource_ = 0;
  clear_has_resource();
}
inline ::google::protobuf::int32 WorldStatusUpdateMessage_Worker::resource() const {
  return resource_;
}
inline void WorldStatusUpdateMessage_Worker::set_resource(::google::protobuf::int32 value) {
  set_has_resource();
  resource_ = value;
}

// optional int32 health = 3;
inline bool WorldStatusUpdateMessage_Worker::has_health() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WorldStatusUpdateMessage_Worker::set_has_health() {
  _has_bits_[0] |= 0x00000004u;
}
inline void WorldStatusUpdateMessage_Worker::clear_has_health() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void WorldStatusUpdateMessage_Worker::clear_health() {
  health_ = 0;
  clear_has_health();
}
inline ::google::protobuf::int32 WorldStatusUpdateMessage_Worker::health() const {
  return health_;
}
inline void WorldStatusUpdateMessage_Worker::set_health(::google::protobuf::int32 value) {
  set_has_health();
  health_ = value;
}

// optional int32 team = 4;
inline bool WorldStatusUpdateMessage_Worker::has_team() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void WorldStatusUpdateMessage_Worker::set_has_team() {
  _has_bits_[0] |= 0x00000008u;
}
inline void WorldStatusUpdateMessage_Worker::clear_has_team() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void WorldStatusUpdateMessage_Worker::clear_team() {
  team_ = 0;
  clear_has_team();
}
inline ::google::protobuf::int32 WorldStatusUpdateMessage_Worker::team() const {
  return team_;
}
inline void WorldStatusUpdateMessage_Worker::set_team(::google::protobuf::int32 value) {
  set_has_team();
  team_ = value;
}

// -------------------------------------------------------------------

// WorldStatusUpdateMessage_Soldier

// optional .strategy_protocol.WorldStatusUpdateMessage.CommonProperties common = 1;
inline bool WorldStatusUpdateMessage_Soldier::has_common() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WorldStatusUpdateMessage_Soldier::set_has_common() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WorldStatusUpdateMessage_Soldier::clear_has_common() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WorldStatusUpdateMessage_Soldier::clear_common() {
  if (common_ != NULL) common_->::strategy_protocol::WorldStatusUpdateMessage_CommonProperties::Clear();
  clear_has_common();
}
inline const ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties& WorldStatusUpdateMessage_Soldier::common() const {
  return common_ != NULL ? *common_ : *default_instance_->common_;
}
inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* WorldStatusUpdateMessage_Soldier::mutable_common() {
  set_has_common();
  if (common_ == NULL) common_ = new ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties;
  return common_;
}
inline ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* WorldStatusUpdateMessage_Soldier::release_common() {
  clear_has_common();
  ::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* temp = common_;
  common_ = NULL;
  return temp;
}
inline void WorldStatusUpdateMessage_Soldier::set_allocated_common(::strategy_protocol::WorldStatusUpdateMessage_CommonProperties* common) {
  delete common_;
  common_ = common;
  if (common) {
    set_has_common();
  } else {
    clear_has_common();
  }
}

// optional int32 health = 2;
inline bool WorldStatusUpdateMessage_Soldier::has_health() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WorldStatusUpdateMessage_Soldier::set_has_health() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WorldStatusUpdateMessage_Soldier::clear_has_health() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WorldStatusUpdateMessage_Soldier::clear_health() {
  health_ = 0;
  clear_has_health();
}
inline ::google::protobuf::int32 WorldStatusUpdateMessage_Soldier::health() const {
  return health_;
}
inline void WorldStatusUpdateMessage_Soldier::set_health(::google::protobuf::int32 value) {
  set_has_health();
  health_ = value;
}

// optional int32 team = 3;
inline bool WorldStatusUpdateMessage_Soldier::has_team() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WorldStatusUpdateMessage_Soldier::set_has_team() {
  _has_bits_[0] |= 0x00000004u;
}
inline void WorldStatusUpdateMessage_Soldier::clear_has_team() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void WorldStatusUpdateMessage_Soldier::clear_team() {
  team_ = 0;
  clear_has_team();
}
inline ::google::protobuf::int32 WorldStatusUpdateMessage_Soldier::team() const {
  return team_;
}
inline void WorldStatusUpdateMessage_Soldier::set_team(::google::protobuf::int32 value) {
  set_has_team();
  team_ = value;
}

// -------------------------------------------------------------------

// WorldStatusUpdateMessage

// repeated .strategy_protocol.WorldStatusUpdateMessage.Base bases = 1;
inline int WorldStatusUpdateMessage::bases_size() const {
  return bases_.size();
}
inline void WorldStatusUpdateMessage::clear_bases() {
  bases_.Clear();
}
inline const ::strategy_protocol::WorldStatusUpdateMessage_Base& WorldStatusUpdateMessage::bases(int index) const {
  return bases_.Get(index);
}
inline ::strategy_protocol::WorldStatusUpdateMessage_Base* WorldStatusUpdateMessage::mutable_bases(int index) {
  return bases_.Mutable(index);
}
inline ::strategy_protocol::WorldStatusUpdateMessage_Base* WorldStatusUpdateMessage::add_bases() {
  return bases_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Base >&
WorldStatusUpdateMessage::bases() const {
  return bases_;
}
inline ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Base >*
WorldStatusUpdateMessage::mutable_bases() {
  return &bases_;
}

// repeated .strategy_protocol.WorldStatusUpdateMessage.Mine mines = 2;
inline int WorldStatusUpdateMessage::mines_size() const {
  return mines_.size();
}
inline void WorldStatusUpdateMessage::clear_mines() {
  mines_.Clear();
}
inline const ::strategy_protocol::WorldStatusUpdateMessage_Mine& WorldStatusUpdateMessage::mines(int index) const {
  return mines_.Get(index);
}
inline ::strategy_protocol::WorldStatusUpdateMessage_Mine* WorldStatusUpdateMessage::mutable_mines(int index) {
  return mines_.Mutable(index);
}
inline ::strategy_protocol::WorldStatusUpdateMessage_Mine* WorldStatusUpdateMessage::add_mines() {
  return mines_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Mine >&
WorldStatusUpdateMessage::mines() const {
  return mines_;
}
inline ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Mine >*
WorldStatusUpdateMessage::mutable_mines() {
  return &mines_;
}

// repeated .strategy_protocol.WorldStatusUpdateMessage.Obstacle obstacles = 3;
inline int WorldStatusUpdateMessage::obstacles_size() const {
  return obstacles_.size();
}
inline void WorldStatusUpdateMessage::clear_obstacles() {
  obstacles_.Clear();
}
inline const ::strategy_protocol::WorldStatusUpdateMessage_Obstacle& WorldStatusUpdateMessage::obstacles(int index) const {
  return obstacles_.Get(index);
}
inline ::strategy_protocol::WorldStatusUpdateMessage_Obstacle* WorldStatusUpdateMessage::mutable_obstacles(int index) {
  return obstacles_.Mutable(index);
}
inline ::strategy_protocol::WorldStatusUpdateMessage_Obstacle* WorldStatusUpdateMessage::add_obstacles() {
  return obstacles_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Obstacle >&
WorldStatusUpdateMessage::obstacles() const {
  return obstacles_;
}
inline ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Obstacle >*
WorldStatusUpdateMessage::mutable_obstacles() {
  return &obstacles_;
}

// repeated .strategy_protocol.WorldStatusUpdateMessage.Worker workers = 4;
inline int WorldStatusUpdateMessage::workers_size() const {
  return workers_.size();
}
inline void WorldStatusUpdateMessage::clear_workers() {
  workers_.Clear();
}
inline const ::strategy_protocol::WorldStatusUpdateMessage_Worker& WorldStatusUpdateMessage::workers(int index) const {
  return workers_.Get(index);
}
inline ::strategy_protocol::WorldStatusUpdateMessage_Worker* WorldStatusUpdateMessage::mutable_workers(int index) {
  return workers_.Mutable(index);
}
inline ::strategy_protocol::WorldStatusUpdateMessage_Worker* WorldStatusUpdateMessage::add_workers() {
  return workers_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Worker >&
WorldStatusUpdateMessage::workers() const {
  return workers_;
}
inline ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Worker >*
WorldStatusUpdateMessage::mutable_workers() {
  return &workers_;
}

// repeated .strategy_protocol.WorldStatusUpdateMessage.Soldier soldiers = 5;
inline int WorldStatusUpdateMessage::soldiers_size() const {
  return soldiers_.size();
}
inline void WorldStatusUpdateMessage::clear_soldiers() {
  soldiers_.Clear();
}
inline const ::strategy_protocol::WorldStatusUpdateMessage_Soldier& WorldStatusUpdateMessage::soldiers(int index) const {
  return soldiers_.Get(index);
}
inline ::strategy_protocol::WorldStatusUpdateMessage_Soldier* WorldStatusUpdateMessage::mutable_soldiers(int index) {
  return soldiers_.Mutable(index);
}
inline ::strategy_protocol::WorldStatusUpdateMessage_Soldier* WorldStatusUpdateMessage::add_soldiers() {
  return soldiers_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Soldier >&
WorldStatusUpdateMessage::soldiers() const {
  return soldiers_;
}
inline ::google::protobuf::RepeatedPtrField< ::strategy_protocol::WorldStatusUpdateMessage_Soldier >*
WorldStatusUpdateMessage::mutable_soldiers() {
  return &soldiers_;
}

// optional int32 resource = 6;
inline bool WorldStatusUpdateMessage::has_resource() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void WorldStatusUpdateMessage::set_has_resource() {
  _has_bits_[0] |= 0x00000020u;
}
inline void WorldStatusUpdateMessage::clear_has_resource() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void WorldStatusUpdateMessage::clear_resource() {
  resource_ = 0;
  clear_has_resource();
}
inline ::google::protobuf::int32 WorldStatusUpdateMessage::resource() const {
  return resource_;
}
inline void WorldStatusUpdateMessage::set_resource(::google::protobuf::int32 value) {
  set_has_resource();
  resource_ = value;
}

// optional int32 myteam = 7;
inline bool WorldStatusUpdateMessage::has_myteam() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void WorldStatusUpdateMessage::set_has_myteam() {
  _has_bits_[0] |= 0x00000040u;
}
inline void WorldStatusUpdateMessage::clear_has_myteam() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void WorldStatusUpdateMessage::clear_myteam() {
  myteam_ = 0;
  clear_has_myteam();
}
inline ::google::protobuf::int32 WorldStatusUpdateMessage::myteam() const {
  return myteam_;
}
inline void WorldStatusUpdateMessage::set_myteam(::google::protobuf::int32 value) {
  set_has_myteam();
  myteam_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace strategy_protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_WorldStatusUpdate_2eproto__INCLUDED
